title: "Chris Barber - Software Architect - Newcastle upon Tyne"
description: "An experienced software architect, primarily working on large scale web applications."
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
