title: "Chris Barber - Software Developer - Newcastle upon Tyne"
description: "An experienced software developer primarily focused on web technologies like Ruby on Rails, JavaScript, CoffeeScript, HTML, SASS"
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
